In [1]:
import requests
import pandas as pd
from io import StringIO
import json 
import csv

In [18]:
# capture data within the tn boarders with longitude and latitude and convert to csv and start the time from 1900 to now
url = 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=csv&minlatitude=34&maxlatitude=37&minlongitude=-90.35&maxlongitude=-80&starttime=1900-01-01&endtime=2020-10-17'

In [19]:
r = requests.get(url)

In [20]:
print(r.text[:1000])

time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,net,id,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
2020-10-16T05:16:13.960Z,36.51,-81.0848333,5.26,-0.33,md,5,272,0.007472,0.2,se,se60312382,2020-10-16T14:15:22.660Z,"3 km E of Sparta, North Carolina",earthquake,1.75,0.75,0.079,4,reviewed,se,se
2020-10-16T02:28:36.570Z,36.1175,-89.7346667,9.95,2.16,md,32,36,0.02656,0.03,nm,nm60312372,2020-10-16T14:03:24.840Z,"9 km ENE of Steele, Missouri",earthquake,0.36,0.54,0.119,25,reviewed,nm,nm
2020-10-15T22:56:55.610Z,36.4733333,-81.0856667,2.34,-0.67,md,4,133,0.008929,0.05,se,se60312367,2020-10-16T14:20:04.400Z,"4 km SE of Sparta, North Carolina",earthquake,0.35,0.81,0.063,4,reviewed,se,se
2020-10-15T04:04:45.570Z,36.4721667,-81.0876667,2.71,-0.56,md,4,140,0.008551,0.04,se,se60312297,2020-10-15T14:49:44.900Z,"4 km SE of Sparta, North Carolina",earthquake,0.39,0.64,0.007,4,reviewed,se,se
2020-10-14T04:02:11.660Z,36.4806667,-81.0885,1.3,-0.

In [21]:
tn_quake_df = pd.read_csv(StringIO(r.text))
tn_quake_df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2020-10-16T05:16:13.960Z,36.510000,-81.084833,5.26,-0.33,md,5.0,272.0,0.007472,0.20,...,2020-10-16T14:15:22.660Z,"3 km E of Sparta, North Carolina",earthquake,1.75,0.75,0.079,4.0,reviewed,se,se
1,2020-10-16T02:28:36.570Z,36.117500,-89.734667,9.95,2.16,md,32.0,36.0,0.026560,0.03,...,2020-10-16T14:03:24.840Z,"9 km ENE of Steele, Missouri",earthquake,0.36,0.54,0.119,25.0,reviewed,nm,nm
2,2020-10-15T22:56:55.610Z,36.473333,-81.085667,2.34,-0.67,md,4.0,133.0,0.008929,0.05,...,2020-10-16T14:20:04.400Z,"4 km SE of Sparta, North Carolina",earthquake,0.35,0.81,0.063,4.0,reviewed,se,se
3,2020-10-15T04:04:45.570Z,36.472167,-81.087667,2.71,-0.56,md,4.0,140.0,0.008551,0.04,...,2020-10-15T14:49:44.900Z,"4 km SE of Sparta, North Carolina",earthquake,0.39,0.64,0.007,4.0,reviewed,se,se
4,2020-10-14T04:02:11.660Z,36.480667,-81.088500,1.30,-0.56,md,4.0,127.0,0.005241,0.05,...,2020-10-14T16:35:04.090Z,"3 km SE of Sparta, North Carolina",earthquake,0.50,0.60,0.005,4.0,reviewed,se,se

In [22]:
# capture the last word in the string wich is the state
tn_quake_df['state'] = tn_quake_df['place'].str[-9:]

In [23]:
# capture the date  
tn_quake_df['date'] = tn_quake_df['time'].str[:10]

In [24]:
# capture the time  
tn_quake_df['time'] = tn_quake_df['time'].str[11:]

In [25]:
# capture the time  
tn_quake_df['time'] = tn_quake_df['time'].str[:8]

In [26]:
tn_quake_df.tail(10)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,state,date
10117,03:05:00,36.0,-90.0,NaN,4.5,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sc,Arkansas,1924-01-01
10118,02:15:00,36.0,-89.2,NaN,4.5,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sg,Tennessee,1918-10-16
10119,05:42:00,36.6,-89.2,NaN,3.8,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,bar,Missouri,1916-12-19
10120,23:39:00,35.5,-82.5,NaN,5.2,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sc,Carolina,1916-02-21
10121,18:40:00,36.0,-90.0,NaN,4.5,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,bar,Arkansas,1915-12-07
10122,21:50:00,36.2,-83.7,NaN,4.1,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sc,Tennessee,1913-03-28
10123,18:28:00,34.7,-81.7,NaN,4.8,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sc,Carolina,1913-01-01
10124,07:10:00,37.0,-89.5,NaN,4.5,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,bar,Missouri,1909-10-23
10125,19:14:00,36.5,-89.8,NaN,5.1,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sc,Missouri,1903-11-04
10126,18:18:00,36.5,-89.5,NaN,4.6,fa,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sc,Tennessee,1903-11-04

In [27]:
tn_quake_df['state'].unique()

array([' Carolina', ' Missouri', 'er region', 'Tennessee', ' Virginia',
       ' Arkansas', ', Georgia', ' Illinois', 'ssissippi', ', Alabama',
       ' Kentucky', 'Missouri', 'Alabama', 'fic Ocean', 'Arkansas'],
      dtype=object)

In [28]:
# remove data that is not Tennessee
#tn_quake_df = tn_quake_df.groupby('state').get_group('Tennessee')

In [43]:
# check that is correct
tn_quake_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4757 entries, 15 to 10126
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             4757 non-null   object
 1   latitude         4757 non-null   float64
 2   longitude        4757 non-null   float64
 3   depth            4752 non-null   float64
 4   mag              4755 non-null   float64
 5   magType          4749 non-null   object
 6   nst              3523 non-null   float64
 7   gap              3521 non-null   float64
 8   dmin             3429 non-null   float64
 9   rms              3530 non-null   float64
 10  net              4757 non-null   object
 11  id               4757 non-null   object
 12  updated          4757 non-null   object
 13  place            4757 non-null   object
 14  type             4757 non-null   object
 15  horizontalError  3563 non-null   float64
 16  depthError       3562 non-null   float64
 17  magError         3508 non-null   float64
 18  magNst           3521 non-null   float64
 19  status           4757 non-null   object
 20  locationSource   4757 non-null   object
 21  magSource        4757 non-null   object
 22  state            4757 non-null   object
 23  date             4757 non-null   object
dtypes: float64(12), object(12)
memory usage: 929.1+ KB

In [37]:
tn_quake_df.shape

(4757, 24)

In [38]:
tn_quake_df.to_csv('cleaned_earthquake_data')

In [39]:
tn_quake_df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,state,date
15,00:54:37,36.141500,-89.457667,11.47,1.25,md,16.0,58.0,0.04641,0.16,...,earthquake,0.48,1.25,0.090,9.0,reviewed,nm,nm,Tennessee,2020-10-13
16,14:41:42,36.168833,-89.463333,11.87,2.06,md,36.0,44.0,0.03136,0.07,...,earthquake,0.24,0.33,0.096,30.0,reviewed,nm,nm,Tennessee,2020-10-12
17,11:33:20,36.345000,-89.516667,5.33,1.33,md,15.0,75.0,0.01536,0.04,...,earthquake,0.29,0.57,0.070,11.0,reviewed,nm,nm,Tennessee,2020-10-12
18,05:37:13,36.297167,-89.535667,10.26,1.45,md,18.0,49.0,0.03705,0.06,...,earthquake,0.41,0.71,0.028,12.0,reviewed,nm,nm,Tennessee,2020-10-12
19,04:16:27,36.295833,-89.534167,9.91,1.39,md,21.0,49.0,0.03885,0.07,...,earthquake,0.19,0.37,0.091,15.0,reviewed,nm,nm,Tennessee,2020-10-12

In [40]:
tn_quake_df[tn_quake_df['mag']== 4.7]

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,state,date
10093,07:48:41,35.799,-83.962,3.0,4.7,mb,NaN,NaN,NaN,NaN,...,earthquake,NaN,NaN,NaN,NaN,reviewed,s,us,Tennessee,1973-11-30

In [42]:
tn_quake_df.to_csv('cleaned_earthquake_df')